@startwbs OBS
* Factory Production Line Project
** C.E.S. International
*** CEO
**** L. Poisson
*** Project management team
**** Project Manager
***** Corentin DEGRES
**** Consultants
***** Bruno DIAS
***** Dany KHADHAR
***** Louis MARGOT
***** Louka MILLON
***** Romaric DEMBELE
***** Théo ROUILLERE

** Mold & Co.
*** Director of New Technology Projects
**** Mrs. Zee
*** R&D Department
*** Design and Engineering Team
*** Production Team
*** Quality Team
*** Maintenance Team
*** Logistics and Supply Chain Team
*** Health and Safety Team
*** Financial Management Team
*** Human Resources Team
*** Marketing and Sales Team
*** Legal and Compliance Team

@endwbs
